### ISSUE TITLE
Allow to disable storing virtual documents on the file system in schema

### ISSUE THREAD

**Issue by krassowski** [jupyter-lsp/jupyterlab-lsp#537]
## What are you trying to do?

Add schema entry which specifies whether virtual documents should be stored on disk for specific language servers.

## How is it done today, and what are the limits of current practice?

We introduced a storage of hard-drive copy of the virtual document on disk because some language servers did not support:
- editing files with extensions other than expected (e.g. ipynb instead of .py for pyls)
- text synchronization for specific operations

with rename feature of pyls/rope as a typical example. While initially allowing to ship features when using faulty servers, this approach has severe impact on other features, especially in servers that do not have such limitations:
- refactoring confuses namespace as we store the virtual documents in `.virtual_documents` directory
- code navigation between files is sometimes impacted (see #275)

## Who cares? If you are successful, what difference will it make?

By allowing to disable this workaround on language-server opt-in basis we can enable more advanced refactoring and navigation features across entire namespace.

## What are the risks?

If servers regress to require a hard copy file or attempt to work on notebooks, we loose the safety net offered by the hard copy virtual documents.

- we need to have the language servers for which we disable the virtual documents mirror storage heavily tested on CI

## How much will it cost?

Ne schema version would be needed.

## How long will it take?

No plans to work on it immediately.

## What are the mid-term and final “exams” to check for success?

New refactoring features work and are tested on CI with namespace-wide edits.

**Comment by bollwyvl** [comment]
Sounds like a good step forward. 

I don't think a new schema version is needed, unless it changes existing behavior in an unexpected way. Recall the last version change was going from language to implementation name for keying the whole `language_servers` object... this hardly seems that drastic.

Because the existing behavior was to do virtual documents for everything, I guess that behavior should be the default. So maybe the new schema is something like:

```yaml
partial-language-server-spec:
  properties:
    ...
    disable_virtual_documents:
      description: Do not write un-saved documents to disk. Well-behaved language servers that work against in-memory files should set this to `true`, which will become the default in the next schema version (3).
      type: boolean
      default: false   
```

Perhaps at that point, it would makes sense to be more precise on the _naming_ of the schema file (which is an implementation detail, to be sure, and not part of the API) so that the existing one would become `v2.schema.json`, with a new `v3.schema.json` where we can start collecting new ideas.
